-- Use SQL insert statements to add any
-- starting/dummy data to your database tables

-- EXAMPLE:

--  insert into "todos"
--    ("task", "isCompleted")
--    values
--      ('Learn to code', false),
--      ('Build projects', false),
--      ('Get a job', false);

insert into "products" ("brand", "name", "style", "image", "details", "amount")
values  ('Adidas', 'ZX 1000', 'sneakers', '/final-project-photos/Adidas - ZX 10000.png', 'In 1984, adidas launched the ZX series, a collection of shoes designed for runners of all types and abilities. the newly designed 10000 C is merely one of many ways that adidas is bringing the ZX franchise up to the present day', '13999'),
 ('Solovair', '8 eye derby', 'boots', '/final-project-photos/Solovair - 8 eye derby.png', 'Black Greasy 8 Eye Derby Boot made of leather using Goodyear welted construction with a signature soft suspension sole.', '21999'),
 ('Asics', 'Gel-Lyte III', 'sneakers', '/final-project-photos/Asics - Gel Lyte iii.png', 'The GEL-LYTE® III OG sneaker emerges once again with its original shape and tooling that it featured in the early 1990s. Designed by Shigeyuki Mitsui, the silhouette retains its iconic split-tongue formation that it debuted with in 1990. This shoe is updated with premium leather details that revamp the model with a modern look. Meanwhile, key components, like its signature GEL® technology unit in the midsole, provide everyday comfort.', '14999'),
 ('Jim Green', 'African Ranger', 'boots', '/final-project-photos/Jim Green - African Ranger.png', 'A designed with 3 main focus areas: Comfort and Durability while at an Affordable price. The wedge sole is designed to grip while the softer rubber compound keeps the Ranger quiet when walking through the African bush', '17999'),
 ('Whites', 'Drifter', 'boots', '/final-project-photos/Whites - Drifter.png', 'The specifications of the Rose Anvil special combine the greatest qualities from Whites legacy models.', '64999'),
 ('Jordan', 'Air Jordan 1', 'sneakers', '/final-project-photos/Jordan-1-chicago.png', 'The Air Jordan 1 Retro High remakes the classic sneaker, giving you a fresh look with a familiar feel. Premium materials with new colors and textures give modern expression to an all-time favorite.', '17999'),
 ('Reebok', 'Question', 'sneakers', '/final-project-photos/Reebok - Question.png', 'Allen Iverson staked his claim as one of the best scorers of his era with a fearless attitude and an unapologetic style. These Reebok shoes are his OG signature style launched in 1996, which makes you a part of sneaker and basketball history when you wear them. All the details you want come included, like a pearlized toe, an ice rubber outsole and a luxe tumbled leather upper.', '14999'),
 ('Grant Stone', 'Diesel Boot', 'boots', '/final-project-photos/Grant Stone - Diesel Boot.png', 'The word diesel doesnt exactly remind us of something flashy but instead of something built for strength and longevity. This is Grant Stones rendition of the basic plain toe boot pattern—made with nothing but proven leather uppers, lining, and insole.', '39500'),
 ('Birkenstock', 'Arizona', 'sandals', '/final-project-photos/Birkenstock - Arizona.png', 'An icon of timeless design and legendary comfort, the Arizona sandal has been defining style since 1973. The laid-back look comes in durable Birko-Flor® for a classic, leather-like finish. Complete with legendary BIRKENSTOCK design elements, like a contoured cork-latex footbed for the ultimate in support.', '11000'),
 ('Brador', 'Eight TDM Sandals', 'sandals', '/final-project-photos/Brador - EIGHT TDM SANDALS.png', ' EIGHT TDMs vegetable tan leather sandals offer a vintage style with a twist. Our signature T/CAPO Brador process ensures each pair is utterly unique, thanks to hand-dyed tints and waxes. As leather is left untreated, natural imperfections are celebrated and the vegetable tanning method is proven to be of superior quality. A work of art for your feet.', '21300'),
 ('Adidas', 'Adilette Slide', 'sandals', '/final-project-photos/Adidas - Adilette Slide.png', 'The Adilette debuted in 1970 as a shower slide for the German national football team during the worlds biggest match in Mexico before being officially released back in 72. Its been a style mainstay of adidas ever since. These slides stay true to the original look with a contoured footbed and 3-Stripes across the bandage upper.', '4000'),
 ('Nike', 'Air Max 1', 'sneakers', '/final-project-photos/Nike - Air Max 1.png', 'Aged neutrals and rich textures work together in updating a celebrated icon. Originally inspired by French architecture, the Air Max 1 is the first shoe in the family that revealed Nike Air to the world. With a fast-paced look, tried-and-true cushioning and wavy mudguard, its no wonder it reigns supreme since 1987.', '14000'),
 ('Jordan', 'Air Jordan 3', 'sneakers', '/final-project-photos/Nike - Air Jordan 3.png', 'Clean and supreme, the AJ3 returns with all of its classic style and grace. Quality leather in the upper—with that luxurious elephant print texture—combines with visible Nike Air in the sole to make a comfortable, everyday icon.', '20000'),
 ('Nike', 'Air Force 1', 'sneakers', '/final-project-photos/Nike - Air Force 1.png', 'The radiance lives on in the Nike Air Force 1 ’07, the b-ball OG that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.', '11000'),
 ('Blackstock & Weber', 'The Ellis Penny Loafer', 'loafers', '/final-project-photos/Blackstock & Weber -The Ellis Penny Loafer.png', ' Blackstock & Weber offers a handmade in Portugal, goodyear welted, full grain leather sourced from Tanneries Du Puy, double Leather sole, gold embossed branding loafer that fits with any modern style', '39500'),
 ('Collegium', 'Pillar Penny', 'loafers', '/final-project-photos/Collegium - Pillar Penny.png', 'The Pillar Penny offers a timeless silhouette, handmade in Italy and crafted with unprecedented materialization.', '25000'),
 ('Collegium', 'Moc Toe Derby', 'loafers', '/final-project-photos/Collegium - Moc Toe Derby.png', 'The Pillar Moc-Toe Derby is Collegiums reimagination of a century old menswear silhouette with their touches of design language.', '27500'),
 ('Alden', '403 indy', 'boots', '/final-project-photos/Alden - 403 Indy.png', 'The Alden 403 Indy Boot in Brown Aniline Pull-Up leather is a moc-toe style boot made from a deep rich brown pull-up leather from Horween thats supple from the start and develops a deeper, richer color with wear.  Made famous by Harrison Ford in Raiders of the Lost Arc, the Alden Indy Boot is the brands most famous and iconic silhouette. This boot began as an orthopedic work boot & features Aldens patented Foot Balance System.', '68000'),
 ('Gucci', 'Jordaan leather loafer', 'dress shoes', '/final-project-photos/Gucci - Jordaan leather loafer.png', 'The leather loafer is designed with an elongated toe and finished by the Houses signature Horsebit detail—an homage to Guccis equestrian roots.', '99000'),
 ('Clarks', 'Wallabee', 'loafers', '/final-project-photos/Clarks - Wallabee.png', 'The Wallabee has become an iconic classic in our Clarks Originals collection across the globe thanks to its moccasin construction and structural silhouette. Featuring clean and simple lines, this comfortable lace-up style is crafted from black leather. The finishing touch is our signature crepe sole which continues to stand the test of time.', '16000'),
 ('Tecovas', 'The Johnny', 'boots', '/final-project-photos/Tecovas - The Johnny.png', 'Long on tradition and confidence, The Johnny is the stalwart of our suede lineup. Made from our treated, water-resistant suede, and shaped into our classic cowboy profile with a round toe, and tastefully angled 1 ½” heel, its a versatile dress boot that will bring rugged elegance to all of your exploits.', '29500'),
 ('Tecovas', 'The Doc', 'boots', '/final-project-photos/Tecovas - The Doc.png', 'The Doc is a down-home dress boot with a classic western profile. It features a broad square toe with signature Tecovas toe stitching, a robust, double-stitched welt, contrasting stitch pattern along the shaft, and a 1 ½” straight heel with just the right amount of ledge for jean stacking.', '29500'),
 ('Adidas', 'Gazelle', 'sneakers', '/final-project-photos/Adidas - Gazelle.png', 'Slip into the past and feel your stride energized with every step. The iconic Gazelle shoes have transcended trends since 1966 to become an adidas classic. Once designed for training, now the suede kicks are a timeless street icon. A textile lining and rubber outsole provide all-day comfort whether youre pounding the pavement or hitting your favorite shops. The Gazelles retro-inspired style will have you channeling the spirit of the 60s. Lace up a piece of adidas heritage and go.', '10000'),
 ('Adidas', 'Ultraboost 1.0', 'sneakers', '/final-project-photos/Adidas - Ultraboost.png', 'From a walk in the park to a weekend run with friends, these adidas Ultraboost 1.0 shoes are designed to keep you comfortable. An adidas PRIMEKNIT upper gently hugs your feet while BOOST on the midsole cushions from the first step to the last mile. The Stretchweb outsole flexes naturally for an energized ride, and Continental™ Rubber gives you the traction you need to keep that pep in your step.', '19000'),
 ('Adidas', 'Samba', 'sneakers', '/final-project-photos/Adidas - Samba.png', 'Born on the pitch, the Samba is a timeless icon of street style. This silhouette stays true to its legacy with a tasteful, low-profile, soft leather upper, suede overlays and gum sole, making it a staple in everyones closet - on and off the pitch.', '10000'),
 ('Beckett Siminon', 'Dean Oxfords', 'dress shoes', '/final-project-photos/Beckett Siminon - Dean Oxfords.png', 'Not only are the Dean Oxfords an important foundation piece of your wardrobe, they are one of the most reliable investments you’ll ever make. This is a shoe that doesn’t ask you to sacrifice quality for price. Even if you don’t wear dress shoes often, you must have at least one pair you can always count on. The Dean Oxfords are that pair. Mostly worn with suits, dressy trousers and nice chinos, the timelessness of the Dean Oxfords will shine through no matter what you pair them with.', '21900'),
 ('Beckett Siminon', 'Hoyt Monkstraps', 'dress shoes', '/final-project-photos/Beckett Siminon - Hoyt Monkstraps.png', 'When double monkstraps first hit the scene, they were looked at as a fun trend. They quickly became a popular alternative to the single monkstrap, and the more traditional Oxfords - and the style has endured for decades. The Hoyt Monkstraps are treasured for their striking appearance and rare nature. With or without socks, they wear extremely well with nice jeans, chinos and suits. The elastic attaching the solid brass buckles to the upper provides flexibility, yet the upper is secure enough so your foot won’t come out while moving. That said, you will be able to slide them on and off with ease. Hoyt Monkstraps are great for the person who wants to showcase their sense of style with confidence.', '21900'),
 ('Reebok', 'Club C', 'sneakers', '/final-project-photos/Reebok - Club C.png', 'Taking their cue from the 80s court classic, these shoes are all about simplicity. They have a leather upper and a timeless easy-to-wear style. The EVA midsole gives you lightweight cushioning.', '9000'),
 ('Reebok', 'Classic Leather', 'sneakers', '/final-project-photos/Reebok - Classic Leather.png', 'Clean, minimalist design keeps your look forever fresh. These Reebok Classic Leather Shoes update the iconic retro style. A supple leather upper and logos pulled from the archives give you trainers that always work, no matter what you pair them with.', '8000'),
 ('Jordan', 'Air Jordan 2', 'sneakers', '/final-project-photos/Jordan - Air Jordan 2.png', 'Making its debut in 1986, the AJ2 was the cool younger sibling of its famous predecessor—a sleeker and more pared-down version of the iconic AJ1. With premium materials and Nike Air cushioning, this throwback serves up the ultimate combo of wearability and style.', '20000'),
 ('Jordan', 'Air Jordan 11', 'sneakers', '/final-project-photos/Jordan - Air Jordan 11.png', 'The upper is designed with a mix of premium materials like luxe leather, along with a smooth knit collar. The glossy patent leather mudguard gleams just like the original. A tinted translucent outsole offers a clean finish while the welded gold Jumpman radiates the shoes championship roots.', '22000'),
 ('Jordan', 'Air Jordan 5', 'sneakers', '/final-project-photos/Jordan - Air Jordan 5.png', 'With its mesh-inspired grid and distinct midsole design, the AJ5 is unmistakable. This version features a mix of full-grain and synthetic leather for texture, plus that iconic lace lock.', '20000'),
 ('Jordan', 'Air Jordan 4', 'sneakers', '/final-project-photos/Jordan - Air Jordan 4.png', 'Heres your AJ4 done up in classic colours. This AJ4 is built to the original specs and constructed of full-grain leather and textiles for a solid feel. And all your favourite AJ4 elements are there, like the floating eyestays and the mesh-inspired side panels and tongue.', '21500'),
 ('Jordan', 'Air Jordan 6', 'sneakers', '/final-project-photos/Jordan - Air Jordan 6.png', 'MJ wore em when he claimed his first championship and youll be wearing em for—well, whatever you want. Laden with dynamic design lines and those iconic lace locks, these sneakers bring throwback style to any fit. Lace up, and let your kicks do the talking.', '21500'),
 ('Wolverine', '1000 mile boot', 'boots', '/final-project-photos/Wolverine - 1000 mile boot.png', 'With a silhouette that’s straight out of 1914 and time-tested Goodyear Welt construction, the 1000 Mile Original Boot is an age-old icon.', '38500'),
 ('Redwing', 'Iron Ranger', 'boots', '/final-project-photos/Redwing - Iron Ranger.png', 'The Iron Ranger is an American icon beloved for its standout style and long-lasting construction. With its toe cap, speed hooks, and Vibram® outsole, theres no mistaking this leather legend.', '34999'),
 ('Redwing', '875 Classic Moc', 'boots', '/final-project-photos/Redwing - 875 Classic Moc.png', 'The 6-inch Classic Moc is synonymous with Red Wing Heritage. The boots unmistakable moc toe and Traction Tred outsole form a silhouette that sets the standard by which all others are measured. Oro Legacy leather uses a unique proprietary blend of oils exclusive to Red Wing, allowing the full-grain texture to remain on display without any added pigment.', '31000'),
 ('Belstaff', 'Trooper Lace Up Boots', 'boots', '/final-project-photos/Belstaff - Trooper Lace Up Boots.png', 'Inspired by lightweight military boots, the Trooper in Ebony oiled leather and lightweight textile is a combat style for those on the move. Paired with a grippy sole, youll be sure-footed in all conditions.', '47500'),
 ('Christian Louboutin', 'Alpinosol Leather Chelsea Boots', 'boots', '/final-project-photos/Christian Louboutin - Alpinosol Leather Chelsea Boots.png', 'Inspired by rugged mountain styles, Christian Louboutins Alpinosol Chelsea boots are expertly crafted from smooth black leather and set on sturdy lug soles for comfort and grip. Theyre finished with signature bright red soles.', '129500'),
 ('Prada', 'Brushed rois leather and Re-Nylon booties', 'boots', '/final-project-photos/Prada - Brushed rois leather and Re-Nylon booties.png', 'An iconic design characterizes these brushed leather booties accented with large inserts in nylon, a distinctive material of Prada. Closed with laces and metal eyelets and hooks, the shoe with a lightweight lug sole is decorated with the enameled metal triangle logo.', '152000'),
 ('Hoka', 'Clifton 9', 'sneakers', '/final-project-photos/Hoka - Clifton 9.png', 'The ninth iteration of Hokas award-winning Clifton franchise has launched, lighter and more cushioned than ever before. Eliminating weight while adding 3mm in stack height, the new Clifton 9 delivers a revitalized underfoot experience with a responsive new foam and improved outsole design. Removing overlays and hotmelts, the stripped back upper has been consciously crafted with a plusher heel, reflective heel panel, and streamlined tongue with single side medial gusset.', '14500'),
 ('New Balance', '9060', 'sneakers', '/final-project-photos/New Balance - 9060.png', 'The 9060 is a new expression of the refined style and innovation-led design that have made the 99X series home to some of the most iconic models in New Balance history. The 9060 reinterprets familiar elements sourced from classic 99X models with a warped sensibility inspired by the proudly futuristic, visible tech aesthetic of the Y2K era. Sway bars, taken from the 990, are expanded and utilized throughout the entire upper for a sense of visible motion, while wavy lines and scaled up proportions on a sculpted pod midsole place an exaggerated emphasis on the familiar cushioning platforms of ABZORB and SBS.', '14999'),
 ('New Balance', '2002r', 'sneakers', '/final-project-photos/New Balance - 2002r.png', 'A premium upper construction offers an elevated take on a classic look.', '14499'),
 ('New Balance', '574', 'sneakers', '/final-project-photos/New Balance - 574.png', 'The most New Balance shoe ever says it all, right? No, actually. The 574 might be our unlikeliest icon. The 574 was built to be a reliable shoe that could do a lot of different things well rather than as a platform for revolutionary technology, or as a premium materials showcase. This unassuming, unpretentious versatility is exactly what launched the 574 into the ranks of all-time greats. As hybrid road/trail design built on a wider last than the previous generations narrow racing silhouettes, the 574 offered a uniquely versatile mix of new, different, uncomplicated, rugged, durable, and comfortable that was adopted as a closet staple across the globe. Thats why today, the 574 is synonymous with the boundary defying New Balance style, and worn by anyone.', '8999'),
 ('New Balance', '990v6 ', 'sneakers', '/final-project-photos/New Balance - 990v6.png', 'The designers of the first 990 were tasked with creating the single best running shoe on the market. The MADE in USA 990v6 embraces this original mandate, with a series of performance-inspired updates. The upper dispenses with the standard midfoot saddle, allowing the pigskin and synthetic overlays to flow from heel to toe across the mesh underlay, for a speedy, streamlined look. While the evolved design marks one of the most dramatic changes from one generation model to the next that the 990 has ever seen, the greatest leap forward occurs on the inside. The addition of FuelCell midsole cushioning means that the evolution of the 990 can be felt as much as it can be seen.', '19999'),
 ('Off-White', 'Out of Office Low Top Sneaker ', 'sneakers', '/final-project-photos/Off-White - Out of Office Low Top Sneaker.png', 'Off-White looks to 80s and 90s athletic shoes to create a modern sneaker that sports a low profile with nods to street, basketball and runner aesthetics.', '65000'),
 ('Prada', 'Americas Cup ', 'sneakers', '/final-project-photos/Prada - Americas Cup.png', 'These patent leather sneakers with bike fabric inserts are inspired by an iconic aesthetic. The unmistakable Prada Linea Rossa logo on the tongue and sole enhances the design.', '89500');



insert into "users" ("hashedPassword", "email")
values ('something', 'stuff');
